### ISSUE TITLE
Fix grunt built and update distro to include recent PRs

### ISSUE THREAD

**Issue by kfarr** [konsumer/randopeep#4]
Any chance you can update this build from the last PR? I can't seem to get grunt to work on my windows machine.

Also the URL of the js min in the readme does not work for HTTPS (http://konsumer.github.io/randopeep/randopeep.min.js redirects to konsumer.js.org which forces HTTP because of certificate mismatch)

As a workaround using this instead which works fine: https://rawgit.com/konsumer/randopeep/gh-pages/randopeep.min.js

**Comment by konsumer** [comment]
Hmm, it seems like the old version of grunt used by randopeep is broken. I have meant to update the code, maybe now is a good opportunity for that. it will take some time, though.

**Comment by kfarr** [comment]
Okay glad it wasn't me. Yeah I tried for 30 mins or so to build it but I'm just not experienced enough with Grunt to diagnose :/

**Comment by konsumer** [comment]
Yeah, totally not just you. The build system is very old and fragile with lots of dead-project deps. I have been thinking about how to package things, too. I think instead of this whole lite/full concept, just distributing full will get everyone where they need to be. I have been doing lots with gRPC lately, so maybe I could spin up a gRPC server + grpc gateway (proxy for HTTP1/JSON) and there'd be lots more options and it'd generally work better and be "lite". I'd also like to be using ES6 to write everything, so this is maybe a chance to really give it an overhaul.

**Comment by kfarr** [comment]
My $0.02 - as a first step to just do a build that concatenates things
together, even not minified, is at least a win.

Also agree the "lite" concept is fun but out of scope of this repo's core
value statement - creating fictional data.

**Comment by konsumer** [comment]
I think this is resolved, feel free to let me know if not.

**Comment by kfarr** [comment]
Working great, thanks!! Using it on this project to create random city names https://github.com/kfarr/aframe-city-builder

**Comment by konsumer** [comment]
nice!
